export const DATABASE_PASSWORD = 'DATABASE_PASSWORD';
export const DATABASE_NAME = 'DATABASE_NAME';
export const JWT_SECRET = 'JWT_SECRET';
export const SERVER_PORT = 'SERVER_PORT';
export const DATABASE_HOST = 'DATABASE_HOST';
export const DATABASE_PORT = 'DATABASE_PORT';
export const DATABASE_USERNAME = 'DATABASE_USERNAME';

export const DEFAULT_USER_EMAIL = 'DEFAULT_USER_EMAIL';
export const DEFAULT_USER_PASSWORD = 'DEFAULT_USER_PASSWORD';
export const DEFAULT_USER_STATE = 'DEFAULT_USER_STATE';
export const DEFAULT_USER_RUT = 'DEFAULT_USER_RUT';
export const DEFAULT_USER_NAME = 'DEFAULT_USER_NAME';
export const DEFAULT_USER_PRIMARY_LAST_NAME = 'DEFAULT_USER_PRIMARY_LAST_NAME';
export const DEFAULT_USER_SECOND_LAST_NAME = 'DEFAULT_USER_SECOND_LAST_NAME';

export const DEFAULT_ROL_NAME = 'DEFAULT_ROL_NAME';
export const DEFAULT_ROL_DESCRIPTION = 'DEFAULT_ROL_DESCRIPTION';
